#+TITLE: CS Notes (Groups)
#+AUTHOR: Firstname Oldroyd
#+EMAIL: oldroyd.j@wvwc.edu
#+DESCRIPTION: CS notes for 2026 Summer Gifted class.
#+KEYWORDS: group theory, Rubik's cube
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:https://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+HTML_LINK_UP:
#+HTML_LINK_HOME:
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LATEX_HEADER: \mode<beamer>{\usetheme{moloch}}
#+LATEX_HEADER: \molochset{block=fill}
#+LATEX_HEADER: \setbeameroption{show notes on second screen}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{logicpuzzle}
#+LATEX_HEADER: \definecolor{codegreen}{rgb}{0,0.6,0}
#+LATEX_HEADER: \definecolor{codegray}{rgb}{0.5,0.5,0.5}
#+LATEX_HEADER: \definecolor{codepurple}{rgb}{0.58,0,0.82}
#+LATEX_HEADER: \definecolor{backcolour}{rgb}{0.95,0.95,0.92}
#+LATEX_HEADER: \lstdefinestyle{pythonstyle}{
#+LATEX_HEADER:   backgroundcolor=\color{backcolour},
#+LATEX_HEADER:   commentstyle=\color{codegreen},
#+LATEX_HEADER:   keywordstyle=\color{magenta},
#+LATEX_HEADER:   numberstyle=\tiny\color{codegray},
#+LATEX_HEADER:   stringstyle=\color{codepurple},
#+LATEX_HEADER:   basicstyle=\ttfamily\footnotesize,
#+LATEX_HEADER:   breakatwhitespace=false,
#+LATEX_HEADER:   breaklines=true,
#+LATEX_HEADER:   captionpos=b,
#+LATEX_HEADER:   keepspaces=true,
#+LATEX_HEADER:   numbers=left,
#+LATEX_HEADER:   numbersep=5pt,
#+LATEX_HEADER:   showspaces=false,
#+LATEX_HEADER:   showstringspaces=false,
#+LATEX_HEADER:   showtabs=false,
#+LATEX_HEADER:   tabsize=2
#+LATEX_HEADER: }
#+LATEX_HEADER: \lstset{%
#+LATEX_HEADER:   language=python,
#+LATEX_HEADER:   numbers=left,
#+LATEX_HEADER:   style=pythonstyle,
#+LATEX_HEADER: }
#+LATEX_HEADER: \newenvironment{fifteen}[1][]{%
#+LATEX_HEADER: \begin{logicpuzzle}[rows=4,columns=4,#1]
#+LATEX_HEADER: \begin{puzzleforeground}
#+LATEX_HEADER: \framepuzzle
#+LATEX_HEADER: \end{puzzleforeground}
#+LATEX_HEADER: }{\end{logicpuzzle}}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

* Introduction
** Python                                                          :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:END:
We will use *Python* in this course to perform mathematical computations.  For the
first part of the computer science course, we will look at how to use Python to
work with groups.  We will primarily interact with Python using the *Spyder* IDE.
** Python Fundamentals                                             :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:END:
The fundamental objects we need from Python are:
- *lists*: ~[obj1, obj2, ...]~
- *functions*: ~def func(x): ...~
* Creating Groups in Python
** A Simple Group in Python                                        :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:END:
Suppose we want to model the coins group of the previous class.  Then we will
need to specify the /objects/ and the /actions/ of the group.  We can use lists
to hold the objects...

#+begin_src python :exports code :session
  # group from 1.1 has as objects arrangements of a penny and a dime
  arrangement1 = ['penny', 'nickel']
  arrangement2 = ['nickel', 'penny']
  objects = [arrangement1, arrangement2]
#+END_src

** A Simple Group in Python                                        :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:END:
...and functions to represent the actions:
#+BEGIN_src python :exports both :session :results output
  # our action takes arrangement1 and turns it into arrangement2, and
  # vice-versa
  def group_action(arrangement):
      if arrangement[0] == 'penny':
          return arrangement2
      else:
          return arrangement1

  # check that this does what we want it to
  for object in objects:
      print(group_action(object))
#+end_src

#+RESULTS:
: ['nickel', 'penny']
: ['penny', 'nickel']

** Group Actions in Python
*** Combining group actions using Python                        :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find the result of performing the group action twice in a row using the code
above.

*** Words group again                                           :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Implement the "three letter words" group in Python.  Be careful to specify the
objects and the actions!
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
There should be six objects and six actions that act on the objects!
** Symmetry Groups in Python
Recall that a symmetry group of a geometric figure is the set of actions that
preserves the shape of that figure.
*** Symmetry group of equilateral triangle                      :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Implement the symmetry group of the equilateral triangle in Python.
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
This is more complicated than previous examples.  Try working out examples by
hand, then implementing in Python with a ~for~ loop.
* Permutations with SymPy
** Permutations in Python
- The SymPy library lets us handle permutations in cycle notation relatively
  easily.
- First, we need to import useful commands as follows:

    #+begin_src python :session :exports code
      from sympy.combinatorics import Permutation
      from sympy.combinatorics import PermutationGroup
      from sympy.combinatorics import SymmetricGroup
  #+end_src
** Computations from \( S_3 \)
- We can now create permutations as follows:
  #+begin_src python :session :exports both :results output
    R = Permutation(1, 2, 3)
  #+end_src
*** Rotation followed by flip                                   :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Let \( R \) denote clockwise rotation of the equilateral triangle by \(
120^{\circ} \) and let \( F \) denote the reflection that leaves vertex \( 1 \)
unchanged.  Using SymPy, find \( R\ast F \) and \( F\ast R \).
** More Computations
*** Klein Four Group                                            :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
The symmetry group of a non-square rectangle is called the /Klein Four Group/.
Create the elements of this group in Python using SymPy as above.  Does the
order of "multiplication" matter in this group?
** Even More Computations
*** Cayley table                                                :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find the Cayley table of the symmetry group of the square
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
Break into four groups; each group tackles two rows of the table
** Parity in SymPy
- SymPy can easily compute the parity of a permutation:
  #+begin_src python :exports both :session
    R.parity() # = 0 since R is even
  #+end_src
** Modified 15-Puzzle
*** Determine existence of solution                             :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Consider the following 15-puzzle:
#+begin_src latex :exports results
  \begin{figure}
      \centering
      \begin{fifteen}
          \setrow{4}{8, 12, 2, 5}
          \setrow{3}{11, 1, 6, 13}
          \setrow{2}{7, 14, 10, 15}
          \setrow{1}{9, 4, 3, }
      \end{fifteen}

      \caption{A modified 15-puzzle}
      \label{fig:modified-fifteen-puzzle}
  \end{figure}
#+end_src
Is it possible to solve this puzzle?  That is, do there exist moves that get the
puzzle back into its solution state?
** Studying the Rubik's Cube Group
- Once we have the permutations of the Rubik's cube group, we can study them
  using SymPy
*** Order of the cube group                                     :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find the order (that is, the size) of the Rubik's cube group.
** Permutations in the Cube Group
*** Permutations and layers                                     :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Explain what the following permutation does to the "cross" on the top layer of a
Rubik's cube:

\[
    R' U F' U'.
\]

Note that \( R' \), \( F' \) and \( U' \) denote /counterclockwise/ turns
instead of clockwise turns.
** Permutations in the Cube Group
*** Filling in corners                                          :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Some algorithms for solving the cube focus on filling in a cross on one layer of
the cube, then on filling in corners on that same layer.  Explain why the
following set of moves is useful for filling in one corner at a time:

\[
    R' D' R D
\]

/Hint/: What does this do to the "cross" on the top layer?  What about the
corner cubies on the same layer?
** Permutations in the Cube Group
*** Finding orders of permutations                              :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
For each of the following moves of the cube, determine how many times you would
need to perform that move in a row to get back to where you started:
1. \( F2*U \) (that is, two front clockwise turns followed by an upper clockwise
   turn).
2. \( F*R \) (that is, a front clockwise turn followed by a right clockwise turn).
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
If you scramble a cube but keep track of the moves you used to scramble it, you
can eventually solve the cube just by performing that same sequence of moves
over and over.
** Moves from Other Moves
- We can check if certain moves can be generated by other moves using the
  ~.contains()~ method:
  #+begin_src python :exports code
    G.contains(P, strict=False) # checks if permutation P is in group G
  #+end_src
** Moves from Other Moves
*** Reducing the number of generators                           :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
So far we've used six generators to construct the cube group.  Show that this
can also be done using five generators.  /Hint/: show that a clockwise front
turn can be accomplished by using some sequence of the other five turns.
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
This can be done with the ~contains~ method on a "subgroup" built out of the
other five motions.
