#+TITLE: Graph Theory Notes
#+AUTHOR: Jesse Oldroyd
#+EMAIL: oldroyd.j@wvwc.edu
#+DESCRIPTION: Graph theory notes for WVWC 2026 summer gifted notes.
#+KEYWORDS: graph theory
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:https://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+HTML_LINK_UP:
#+HTML_LINK_HOME:
#+startup: beamer
#+LaTeX_CLASS: beamer
#+latex_header: \mode<beamer>{\usetheme{moloch}}
#+LATEX_HEADER: \molochset{block=fill}
#+LATEX_HEADER: \setbeameroption{show notes on second screen}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{logicpuzzle}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{graphs}
#+LATEX_HEADER: \usepackage{tkz-graph}
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \lstdefinestyle{pythonstyle}{
#+LATEX_HEADER:   backgroundcolor=\color{backcolour},
#+LATEX_HEADER:   commentstyle=\color{codegreen},
#+LATEX_HEADER:   keywordstyle=\color{magenta},
#+LATEX_HEADER:   numberstyle=\tiny\color{codegray},
#+LATEX_HEADER:   stringstyle=\color{codepurple},
#+LATEX_HEADER:   basicstyle=\ttfamily\footnotesize,
#+LATEX_HEADER:   breakatwhitespace=false,
#+LATEX_HEADER:   breaklines=true,
#+LATEX_HEADER:   captionpos=b,
#+LATEX_HEADER:   keepspaces=true,
#+LATEX_HEADER:   numbers=left,
#+LATEX_HEADER:   numbersep=5pt,
#+LATEX_HEADER:   showspaces=false,
#+LATEX_HEADER:   showstringspaces=false,
#+LATEX_HEADER:   showtabs=false,
#+LATEX_HEADER:   tabsize=2
#+LATEX_HEADER: }
#+LATEX_HEADER: \lstset{%
#+LATEX_HEADER:   language=python,
#+LATEX_HEADER:   numbers=left,
#+LATEX_HEADER:   style=pythonstyle,
#+LATEX_HEADER: }
#+LATEX_HEADER: \newenvironment{fifteen}[1][]{%
#+LATEX_HEADER: \begin{logicpuzzle}[rows=4,columns=4,#1]
#+LATEX_HEADER: \begin{puzzleforeground}
#+LATEX_HEADER: \framepuzzle
#+LATEX_HEADER: \end{puzzleforeground}
#+LATEX_HEADER: }{\end{logicpuzzle}}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

* Introduction to Graph Theory
** Networks and Relationships
- Much like group theory is the mathematical language of symmetry, graph theory
  provides languages for expressing relationships
*** Applications of graph theory
- Modeling networks
- Chemistry
- Machine learning
- Routing problems
- CYOA
** Terminology
- A *graph* \( \mathcal{G} = (V, E) \) is a set \( V \) of *vertices* together
  with a set \( E \) of *edges*.  Two vertices are *adjacent* or neighbors if
  they are connected by an edge.
- A *simple graph* is a graph with at most one edge between any pair of vertices
  and no loops.
  #+begin_src latex :exports results
    \begin{figure}
        \centering
        \begin{subfigure}{.4\textwidth}
            \caption{A graph that is not simple.}
            \begin{tikzpicture}[scale=1]
                \GraphInit[vstyle=normal]
                \Vertex{A}
                \Vertex[x=4,y=0]{B}
                \Vertex[x=1,y=2]{C}
                \Edge[style={bend left}](B)(A)
                \Edges(A,B,C,A)
            \end{tikzpicture}
        \end{subfigure}
        \begin{subfigure}{.4\textwidth}
          \caption{A simple graph.}
            \begin{tikzpicture}[scale=1]
                \GraphInit[vstyle=normal]
                \Vertex{A}
                \Vertex[x=4,y=0]{B}
                \Vertex[x=1,y=2]{C}
                \Edges(A,B,C,A)
            \end{tikzpicture}
        \end{subfigure}
    \end{figure}
  #+end_src
** Friendship
- A friendship graph is a graph where each pair of vertices have exactly one
  neighbor (i.e., the "friend") in common.
*** Friendship graphs                                           :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Draw examples of friendship graphs.
** Degrees, Paths and Cycles
- The *degree* of a vertex is the number of edges adjacent to that vertex.  A
  *path* between two vertices is a series of distinct, adjacent vertices that
  connects the vertices.  A *cycle* is a path that starts and ends at the same
  vertex.
** An Example
*** Finding degrees, paths and cycles                           :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find the following using the graph below:
1. The degree of each vertex.
2. The number of paths from vertex 1 to vertex 6.
3. The length of the shortest path from vertex 1 to vertex 6.
#+begin_src latex :exports results
  \begin{figure}
      \centering
      \caption{A graph that is not simple.}
      \begin{tikzpicture}[scale=1]
          \GraphInit[vstyle=normal]
          \Vertex{1}
          \SOWE(1){2}
          \SOEA(2){3}
          \WE(3){4}
          \NOWE(2){5}
          \NOEA(3){6}
          \NOWE(6){7}
          \Edges(1,4,2,5,1,2)
          \Edges(4,5,7,2,4)
          \Edges(4, 3, 7)
          \Edge(7)(6)
      \end{tikzpicture}
  \end{figure}
#+end_src
** An Application
*** Scheduling tournaments                                      :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Suppose six teams are playing in a tournament and each team must play exactly
three others.  How can this be done?  What if only five teams are playing?
** An Impossibility Proof
*** Not scheduling tournaments                                  :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Prove that it's impossible to schedule a tournament for five teams such that
each team plays exactly three others.
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
Look at previous examples and try to find a relationship between degrees and
edges.
** Another Matching Problem
*** Utility graph                                               :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Three houses \( A \), \( B \) and \( C \) must be connected to three utilities
\( E \) (electric), \( G \) (gas) and \( W \) (water).  Each house must
connected to each utility exactly once.  What graph represents this situation?
** Bipartite Graphs
- A *bipartite graph* is a graph with one group of \( m \) vertices and another
  group of \( n \) vertices such that each vertex is adjacent to all of the
  vertices in the other group and adjacent to none of the vertices in their own
  group.  This graph is denoted by \( K_{m,n} \).
- The utility graph is \( K_{3,3} \).
** Stable Matchings
*** Employment                                                  :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Suppose that four employers (labeled \( A,B,C,D \)) are recruiting from a shared
pool of four applicants (labeled \( 1,2,3,4 \)).  The employers and applicants
have ranked each other as follows:
| Applicant | Employer rankings | Employer | Applicant rankings |
|-----------+-------------------+----------+--------------------|
|         1 | A, B, C, D        | A        | 4, 2, 1, 3         |
|         2 | A, B, D, C        | B        | 2, 1, 3, 4         |
|         3 | B, A, C, D        | C        | 1, 3, 4, 2         |
|         4 | D, A, B, C        | D        | 1, 3, 2, 4         |
Employers will make offers to applicants, but applicants are allowed to
change their minds if a better offer comes along.  Is there a /stable matching/,
i.e., a situation where no applicant will change their mind?
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
An example of an unstable matching is the following:
#+begin_src latex :exports results
  \begin{figure}
      \centering
      \caption{A matching that is not stable.}
      \begin{tikzpicture}[scale=1]
          \GraphInit[vstyle=normal]
          \Vertex{1}
          \EA(1){2}
          \EA(2){3}
          \EA(3){4}
          \NO(1){A}
          \EA(A){B}
          \EA(B){C}
          \EA(C){D}
          \Edge(A)(1)
          \Edge(B)(2)
          \Edge(C)(4)
          \Edge(D)(3)
      \end{tikzpicture}
  \end{figure}
#+end_src
This is because \( A \) prefers \( 2 \) to \( 1 \) and \( 2 \) prefers \( A \)
to \( B \).  Therefore, both are inclined to switch.
** Stable Matching Algorithm
- The previous problem can be solved by an algorithm.  For each round:
  1. Each employer with an open position makes an offer to the best candidate
     that they haven't made an offer to yet.
  2. Each applicant evaluates their offers and tentatively selects the best
     offer while rejecting the others.
  3. If there are any open positions remaining, then repeat this process in a
     new round of offers.
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
This is known as the [[https://en.wikipedia.org/wiki/Gale%E2%80%93Shapley_algorithm][Gale-Shapley algorithm]].  It had previously been used to
match residents with hospitals.
