#+TITLE: Group Theory Notes
#+AUTHOR: Firstname Oldroyd
#+EMAIL: oldroyd.j@wvwc.edu
#+DESCRIPTION: Group theory notes for WVWC 2026 summer gifted notes, based on Visual Group Theory.
#+KEYWORDS: group theory
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:https://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+HTML_LINK_UP:
#+HTML_LINK_HOME:
#+startup: beamer
#+LaTeX_CLASS: beamer
#+latex_header: \mode<beamer>{\usetheme{moloch}}
#+LATEX_HEADER: \molochset{block=fill}
#+LATEX_HEADER: \setbeameroption{show notes on second screen}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{logicpuzzle}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \lstdefinestyle{pythonstyle}{
#+LATEX_HEADER:   backgroundcolor=\color{backcolour},
#+LATEX_HEADER:   commentstyle=\color{codegreen},
#+LATEX_HEADER:   keywordstyle=\color{magenta},
#+LATEX_HEADER:   numberstyle=\tiny\color{codegray},
#+LATEX_HEADER:   stringstyle=\color{codepurple},
#+LATEX_HEADER:   basicstyle=\ttfamily\footnotesize,
#+LATEX_HEADER:   breakatwhitespace=false,
#+LATEX_HEADER:   breaklines=true,
#+LATEX_HEADER:   captionpos=b,
#+LATEX_HEADER:   keepspaces=true,
#+LATEX_HEADER:   numbers=left,
#+LATEX_HEADER:   numbersep=5pt,
#+LATEX_HEADER:   showspaces=false,
#+LATEX_HEADER:   showstringspaces=false,
#+LATEX_HEADER:   showtabs=false,
#+LATEX_HEADER:   tabsize=2
#+LATEX_HEADER: }
#+LATEX_HEADER: \lstset{%
#+LATEX_HEADER:   language=python,
#+LATEX_HEADER:   numbers=left,
#+LATEX_HEADER:   style=pythonstyle,
#+LATEX_HEADER: }
#+LATEX_HEADER: \newenvironment{fifteen}[1][]{%
#+LATEX_HEADER: \begin{logicpuzzle}[rows=4,columns=4,#1]
#+LATEX_HEADER: \begin{puzzleforeground}
#+LATEX_HEADER: \framepuzzle
#+LATEX_HEADER: \end{puzzleforeground}
#+LATEX_HEADER: }{\end{logicpuzzle}}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

* Introduction
** Rubik's Cube
*** Rubik's cube                                                :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Consider the Rubik's cube (for an online example, see [[https://onlinecube.com/][here]]).  What moves can we
perform on a Rubik's cube?

*** Rules of moves                                                :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
There are many, /many/ different configurations (or states) possible, but only
one solution.  We can get from one state to another by performing a valid
movement of the cube.  These movements have the following properties:
1. There is an unchanging list of allowable moves.
2. Every move is reversible.
3. Every move is deterministic.
4. Moves can be combined.

** Rubik's Cube

*** Generators of Rubik's cube motions                          :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
The website above uses twelve basic moves: \( \mathsf{F} \), \( \mathsf{F}' \),
 \( \mathsf{U} \), \( \mathsf{U}' \), and so on.
 - How can you write \(\mathsf{F}' \) in terms of \( \mathsf{F} \)?
 - What is the smallest number of moves you can find that represent all of the
   basic moves on a Rubik's cube?

** Groups                                                          :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:END:
The observations above form the basis of a mathematical structure called a
*group*.  Groups appear throughout mathematics and its applications.

* Examples of Groups
** Swaps
*** Coins in a line                                             :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Consider placing a penny and a nickel side by side in front of you.  Is the
action of swapping the positions of both coins a group?  Note that you will
need to specify an appropriate list of moves and determine if that list
satisfies the above rules.

*** Marbles in piles                                            :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Suppose you have five marbles in each of two piles in front of you.  You have
two actions available to you: you can take a marble from the left pile and move
it to the right pile, /or/ you can take a marble from the right pile and add it
to the left pile.  Is this a group?
** Actions on Words
*** Three letter words                                          :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Consider all possible three letter "words" that can be formed from the letters
 \( \{A, B, C\} \), where each letter must be used precisely once.
 a) How many words are possible?
 b) Consider two actions: swapping the first and second letter of a word, and
    swapping the second and third letter of a word.  Can these two actions alone
    generate all of the words possible starting from \( ABC \)?
 c) Is this a group?
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
End of class <2026-06-22 Mon>
** Group Theory                                                    :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:END:
At this point, you might start thinking of a group as a set of objects that we
can move around in a nice way.  Group theory is about the study of such sets
following the rules outlined above.

*** Coins in a line (again)                                     :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Consider the group of coins in a line.
a) By rule 4, the action from this exercise when performed twice in a row yields
   another action in the group.  What is this action?
b) Does every group have an action like this?

**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
As a reminder, the group rules are as follows:
1. There is an unchanging list of moves.
2. Every move is reversible.
3. Every move is deterministic.
4. Moves can be combined.

** Examples of Groups
*** Symmetry groups                                             :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Describe the symmetry group of an equilateral triangle and a non-square
rectangle.
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
Recall that the symmetry group of a shape is the set of reflections/rotations
that leaves the shape unchanged.
** Groups with Certain Properties
*** Groups with restrictions                                    :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Try to find or construct groups that satisfy the following constraints:
a) The order in which the actions are performed matters.
b) The order in which the actions are performed doesn't matter.
c) There are exactly three actions.
d) There are exactly four actions.
e) There are infinitely many actions.
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
a) Rubik's cube group or symmetry group of triangle/square
b) Symmetry group of non-square rectangle or coin group
c) Look at triangle
d) Look at square or non-square rectangle
e) Can use the integers or an infinite chain
** Nonexamples of Groups
*** Sets that break group rules                                 :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Devise a situation that satisfies all of the group rules except for the second,
third or fourth depending on your group.
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
Break class into three groups (count off 1, 2, 3) and have the groups focus on
breaking a single rule from group rules.
a) Breaks second rule: can use naturals with addition or an action that "erases"
   information.
b) Think of symmetry group where we rotate or flip based on results of coin toss.
c) We already have an example of this.  We can also look at limited symmetry
   groups (i.e., subgroups that aren't closed).
* Permutations
** Permutations
- A *permutation* of an ordered collection of objects is a rearrangement of
  those objects.
- Every group action we've looked at so far is an example of a permutation.
*** Permutations and groups                                     :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
List the permutations and the objects being permuted for the following groups:
1. The three letter word group (see [[*Three letter words][Example (Three letter words)]]).
2. The symmetry group of the equilateral triangle (see [[*Symmetry groups][Symmetry Groups (slide)]]).
** Symmetry Groups
- Shapes have symmetry groups (also called /dihedral groups/).
- Collections of objects also have symmetry groups.  The actions are
  permutations.
*** Elements of a symmetry group                                :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Give two elements of the symmetry group of \( \{1, 2, 3, 4\} \).
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
Note the connection to previous permutations!
*** Number of elements of a symmetry group                      :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
How many elements are in the symmetry group above?
** Composition of Permutations
- Two permutations on the same set of elements can be combined.
*** Combining permutations                                      :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Let
#+begin_src latex :exports results
  \[
      \sigma = \left(
      \begin{array}{llllll}
        1 & 2 & 3 & 4 & 5 & 6 \\
        3 & 5 & 4 & 6 & 2 & 1
      \end{array}
  \right), \rho = \left(
      \begin{array}{llllll}
        1 & 2 & 3 & 4 & 5 & 6 \\
        3 & 1 & 4 & 6 & 2 & 5
      \end{array}
  \right)
  \]
#+end_src
Find \( \sigma\rho \).
** Cycle Notation
- The permutation \( \sigma\in S_3 \) given by

#+begin_src latex :exports results
  \[
      \left( \begin{array}{lll}
        1 & 2 & 3 \\
        2 & 3 & 1
      \end{array} \right)
  \]
#+end_src
can be written as \( (231) \).
*** More cycles
Write the permutations \( \sigma \) and \( \rho \) from [[*Combining permutations][Example: Combining
permutations]] using cycle notation.
** \( S_n \)
- The symmetry group on \( n \) elements is called \( S_n \).
- You've already found \( S_3 \)!
- Permutations in \( S_n \) can be written in cycle notation.
** Cycle Notation Again
*** Cycle notation in \( S_4 \)                                 :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Write the permutations you found in [[*Elements of a symmetry group][Example (Elements of a symmetry group)]] using
cycle notation.
** Combining Permutations Again
- Cycle notation provides a convenient way to combine permutations.
*** Combining permutations with cycles                          :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find \( \sigma\rho \) using cycle notation.
** Cayley Tables
A *Cayley table* is a multiplication table for a group.
*** Cayley table for symmetry group                             :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find the Cayley table for the symmetry group of the rectangle
** Cayley Tables
*** Cayley table for \( S_3 \)                                  :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find the Cayley table for \( S_3 \) (i.e., the symmetry group of the equilateral
triangle).
** Even and Odd Permutations
- Permutations can be categorized as *even* or *odd* based on how many
  switches they perform
- This is called the *parity* of the permutation
*** Determine parity in \( S_3 \)                               :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find the parity of the permutations \( (12) \) and \( (123) \).
*** Determine parity in \( S_6 \)                             :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Find the parity of the permutations \( \sigma \), \( \rho \) and \( \sigma\rho \).
** Permutation Puzzles
- Many classic puzzles (including the Rubik's Cube) can be described in terms of
  permutations
- Knowing something about the allowed permutations tells us about the puzzle itself!
- These puzzles often have *invariants* that we can use to analyze them
** Mutilated Chessboard Puzzle
- The Mutilated Chessboard Puzzle asks if it is possible to cover a chessboard
with two opposite corners removed using \( 2\times1 \) dominoes.
** Mutilated Chessboard Puzzle
#+begin_src latex :exports results
  % Taken from
  % https://tex.stackexchange.com/a/414006/60075
  \begin{figure}
      \label{fig:mutilated_chessboard}
      \begin{center}
          \begin{tikzpicture}[scale=0.5, transform shape]
              \foreach \x in {0,...,7} \foreach \y in {0,...,7}
              {
                \pgfmathparse{mod(\x+\y,2) ? "black" : "white"}
                \edef\colour{\pgfmathresult}
                % This one for the bottom-left and top-right corners
                % \ifnum\x=\y
                %     \ifnum\x=7
                %         \def\colour{black}
                %     \else\ifnum\x=0
                %             \def\colour{black}
                %         \fi\fi
                % \fi
                % % % % % %
                % And this one for the top-left and bottom-right corners
                \ifnum\x=\numexpr\y-7
                    \ifnum\x=0
                        \def\colour{white}
                    \fi
                \fi
                \ifnum\y=\numexpr\x-7
                    \ifnum\y=0
                        \def\colour{white}
                    \fi
                \fi
                % % % % % %
                \path[fill=\colour] (\x,\y) rectangle ++ (1,1);
              }
              \draw (0,0)--(0,8)--(8,8)--(8,0)--cycle;
              \draw (0,7)--(1,7)--(1,8);
              \draw (7,0)--(7,1)--(8,1);
          \end{tikzpicture}
          \caption{Chessboard with two corner pieces missing.}
      \end{center}
  \end{figure}
#+end_src
** Invariants and Solvability
- No matter how you place dominoes on the chessboard, there is something that
  must be true of each domino.  This is an invariant of the puzzle.
*** Impossibility of solution                                   :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Explain why the chessboard puzzle is not solvable.  /Hint/: find an invariant
for the puzzle, i.e., something that must be true no matter how you place
dominoes on the puzzle.
** The 15-Puzzle
- The goal is to solve the puzzle to put the numbers in order (i.e., swap the
  14 and 15 squares)

- The blank square must be on the bottom right at the end
  #+begin_src latex :exports results
    \begin{figure}
        \centering
        \begin{fifteen}
            \setrow{4}{1,2,3,4} \setrow{3}{5,6,7,8} \setrow{2}{9,10,11,12}
            \setrow{1}{13,15, 14, }
        \end{fifteen}

        \caption{The 15-puzzle}
        \label{fig:fifteen-puzzle}
    \end{figure}
  #+end_src
** "A Pestilence"
\begin{figure}
\centering
\includegraphics[scale=0.65]{fifteen_puzzle.png}

\caption{Excerpt from New York Times, 1880}
\end{figure}
** Permutations and the 15-Puzzle
*** Model a configuration                                       :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Use a permutation to describe the following arrangement of the 15-puzzle:
#+begin_src latex :exports results
  \begin{figure}
    \centering
    \begin{fifteen}
        \setrow{4}{8, 12, 2, 5}
        \setrow{3}{11, 1, 6,}
        \setrow{2}{7, 14, 10, 15}
        \setrow{1}{9, 4, 3, 13}
    \end{fifteen}

    \caption{A shuffled 15-puzzle}
    \label{fig:shuffled-fifteen-puzzle}
  \end{figure}
#+end_src
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
The allowed moves of the 15-puzzle do /not/ form a group!
** Parity Again
*** Find parity of configurations                               :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Determine the parities of the permutations corresponding to the puzzles in the
previous examples, and find the parity of the solution of the 15-puzzle.
*** Parity of moves in the 15-puzzle
Every valid configuration in the 15-puzzle (that is, moves that place the empty spot in
position 16) corresponds to an even permutation.
** Impossibility of the 15-Puzzle
*** Nonexistence of solution                                    :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:
There is no solution of the 15-puzzle.
** Variation of the 15-Puzzle
*** Empty square on bottom left                                 :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Suppose we don't want the empty square to end up on the bottom right, but rather
the bottom left:
#+begin_src latex :exports results
  \begin{figure}
      \centering
      \begin{fifteen}
          \setrow{4}{1,2,3,4}
          \setrow{3}{5,6,7,8}
          \setrow{2}{9,10,11,12}
          \setrow{1}{,13,14,15}
      \end{fifteen}

      \caption{The modified 15-puzzle.}
      \label{fig:fifteen-puzzle-variation}
  \end{figure}
#+end_src
Is the puzzle now solvable?
* Rubik's cube group
** Terminology                                                     :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:END:
The *cubies* on a Rubik's cube can be placed in the following categories:
1. Corner cubies
2. Edge cubies
3. Center cubies
** Cubies and Cubicles                                             :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:END:
- A *cubicle* is the position of a given cubie.  Moves changes the positions of
  the cubies, but /not/ the cubicles.
- Positions can be specified by listing incident faces: \( \mathsf{u} \mathsf{f}
  \mathsf{r}\) represents the cubicle/cubie on the upper front right face (i.e.,
  a corner).
*** Edge Positions                                              :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Give all positions for edge cubies on the back face of a cube.
** Group Actions and Cubies
*** Generators Acting on Cubies                                 :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
What happens to cubies in the previous categories if you apply any of the six
basic Rubik's cube actions?
** Estimating Rubik's Cube Group
*** Size of the Rubik's cube group                              :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
The Rubik's cube group is based on the six fundamental motions \( \mathsf{F} \),
\( \mathsf{B} \), \( \mathsf{U} \), \( \mathsf{D} \), \( \mathsf{L} \) and \(
\mathsf{R} \).  How large could this group be?  /Hint/: try answering the
following questions.
1. How many different positions can the corner cubies be in?
2. How many different positions can the edge cubies be in?
*** Notes                                                        :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
1. The corner cubies can be arranged in up to \( 8! \) ways with up to \( 3 \)
  different configurations each, giving an upper bound of \( 8!3^8 \)
  arrangements for the corner cubies.
2. The edge cubies have an upper bound of \( 12! 2^{12} \) arrangements.
3. The upper bound for moves is therefore \( 8! 3^8 12! 2^{12} \).
** Implementing the Cube Group
- The cube group is generated by the actions \( F, B, U, D, L, R \).
*** Describing actions                                          :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
Give the permutations that correspond to the above actions.
**** Note                                                       :B_noteNH:
:PROPERTIES:
:BEAMER_env: noteNH
:END:
Work through permutation for \( B \) as a class as follows:
1. List all numbers on layer back layer.
2. Go through and trace the path of one number at a time.  Remove numbers from
   list as you do.
3. The answer is
   \[ B = (1, 14, 48, 27)(2, 12, 47, 29)(3, 9, 46, 32)(33, 35, 40, 38)(34, 37,
   39, 36) \]
